import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";
import { Container } from "@mui/material";
import Header from "./components/shared/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`} style={{ margin: "0px" }}>
        <Header />
        <NavBar />
        <Container className="min-h-screen">{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
